//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StonePlusCalc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stone
    {
        public int StoneID { get; set; }
        public string Code { get; set; }
        public Nullable<double> Convert { get; set; }
    }
}
